# 工厂的几个实例化, 用户可按如下方式指定自己的实例,指定优化方法solver和正则化项reg即可

## 使用LM方法优化带有一范数约束的优化问题
LM_IRLS:
  solver:
    name: 'LM'
    iters: 100
    lamb: 0.001
    step_size: 6 # 步长
  reg:
    name: 'IRLS'
    alpha: 0.01
    eps: 0.1

## 使用高斯牛顿方法优化带有一范数约束的优化问题
GN_IRLS:
  solver:
    name: 'GN'
    iters: 100
    step_size: 0.2
  reg:
    name: 'IRLS'
    alpha: 0.00002
    eps: 0.01

# TODO Split Bregman有一些问题还未解决
SB_TV:
  solver:
    name: 'SB'
    iters_outer: 10
    sub1:
      name: 'LM'
      iters: 10
      lamb: 0.001
      step_size: 3
  reg:
    name: 'User_L2'
    alpha: 0.002
    tau: 1
    lamb: 0.001

GD:
  solver:
    name: 'GD'
    iters: 100
    milestone: []
    step_size: [[0.2,0.2,0.1]]
#    step_size1: [10000,10000,5000]
  reg:
    name: 'IRLS'
    alpha: 0.1
    eps: 0.0001

GD_IRLS:
  solver:
    name: 'GD'
    iters: 200
    step_size: 6000 # 步长
  reg:
    name: 'IRLS'
    alpha: 0.01
    eps: 0.1

LM:
  solver:
    name: 'LM'
    iters: 200
    lamb: 0.001
    step_size: 14 # 步长
  reg:
    name: 'NoReg'
    alpha: 0.01
    eps: 0.1
