LM_IRLS:
  solver:
    name: 'LM'
    iters: 100
    lamb: 0.001
    step_size: 6 # 步长
  reg:
    name: 'IRLS'
    alpha: 0.01
    eps: 0.1

GN_IRLS:
  solver:
    name: 'GN'
    iters: 100
    step_size: 0.2
  reg:
    name: 'IRLS'
    alpha: 0.00002
    eps: 0.01

SB_TV:
  solver:
    name: 'SB'
    iters_outer: 10
    sub1:
      name: 'LM'
      iters: 10
      lamb: 0.001
      step_size: 3
  reg:
    name: 'User_L2'
    alpha: 0.002
    tau: 1
    lamb: 0.001
